# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user_packages', '0001_initial'), ('user_packages', '0002_auto_20160712_2132'), ('user_packages', '0003_auto_20160726_1945'), ('user_packages', '0004_booking'), ('user_packages', '0005_auto_20160727_1145'), ('user_packages', '0006_auto_20160727_1251'), ('user_packages', '0007_auto_20160727_1428'), ('user_packages', '0008_auto_20160727_1447'), ('user_packages', '0009_auto_20160727_1630'), ('user_packages', '0010_auto_20160727_1630'), ('user_packages', '0011_auto_20160802_1752')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Event Name', max_length=250, unique=True, verbose_name='event name')),
                ('slug', models.CharField(help_text='-nated Event Name', max_length=255, unique=True, verbose_name='event slug')),
                ('date', models.DateField()),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='who can manage this event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user_packages.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary of the booking')),
                ('filename', models.CharField(max_length=150)),
                ('amount', models.FloatField(default=0.0, verbose_name='Event cost')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('IP', 'In Progress'), ('CP', 'Completed')], default='CR', max_length=2)),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Stripe payment date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='user_packages.Event')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='user_packages.EventPackage')),
                ('slug', models.SlugField(help_text='-nated Name for referring to this                            booking', max_length=255, unique=True, verbose_name='booking slug')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='-nated Event Name', max_length=255, unique=True, verbose_name='event slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='who can manage this event'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=150, verbose_name='stripe payment id')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('response', models.TextField(verbose_name='json response')),
                ('payment_date', models.DateTimeField(verbose_name='payment date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user_packages.Booking')),
            ],
        ),
    ]
