# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackages',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 7, 12, 19, 32, 32, 906009, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpackages',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
