# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_packages', '0002_auto_20160712_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Event Name', max_length=250, unique=True, verbose_name='event name')),
                ('slug', models.CharField(help_text='-nated Event Name', max_length=255, unique=True, verbose_name='event slug')),
                ('date', models.DateField()),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='who can manage this event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user_packages.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpackages',
            name='owner',
        ),
        migrations.DeleteModel(
            name='UserPackages',
        ),
    ]
