# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0003_auto_20160726_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary of the booking')),
                ('filename', models.CharField(max_length=150)),
                ('amount', models.FloatField(verbose_name='Event cost')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('IP', 'In Progress'), ('CP', 'Completed')], max_length=2)),
                ('payment_Date', models.DateTimeField(verbose_name='Stripe payment date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_packages.Event')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_packages.EventPackage')),
            ],
        ),
    ]
