# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0004_auto_20160820_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='-nated Event Name', unique=True, verbose_name='event slug'),
        ),
    ]
