# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_Date',
            new_name='payment_date',
        ),
    ]
