# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0005_auto_20160727_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 7, 27, 10, 51, 19, 451450, tzinfo=utc), help_text='-nated Event Name', max_length=255, unique=True, verbose_name='event slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='-nated Event Name', max_length=255, unique=True, verbose_name='event slug'),
        ),
    ]
