# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0005_auto_20160917_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='send_invite',
            field=models.BooleanField(default=False, verbose_name='Can Send Invite'),
        ),
    ]
