# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0006_auto_20160727_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(help_text='-nated Name for referring to this booking', max_length=255, unique=True, verbose_name='event slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='who can manage this event'),
        ),
    ]
