# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0007_auto_20160727_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='user_packages.Event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='user_packages.EventPackage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(help_text='-nated Name for referring to this booking', max_length=255, unique=True, verbose_name='booking slug'),
        ),
    ]
