# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0008_auto_20160727_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Event cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IP', 'In Progress'), ('CP', 'Completed')], default='CR', max_length=2),
        ),
    ]
