# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0009_auto_20160727_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stripe payment date'),
        ),
    ]
