# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_packages', '0010_auto_20160727_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=150, verbose_name='stripe payment id')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('response', models.TextField(verbose_name='json response')),
                ('payment_date', models.DateTimeField(verbose_name='payment date')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(help_text='-nated Name for referring to this                            booking', max_length=255, unique=True, verbose_name='booking slug'),
        ),
        migrations.AddField(
            model_name='payments',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user_packages.Booking'),
        ),
    ]
