# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_packages', '0004_auto_20160820_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('attending', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No'), ('MB', 'Maybe')], default='YS', max_length=2)),
                ('num_of_adults', models.IntegerField()),
                ('num_of_children', models.IntegerField()),
                ('message', models.TextField(verbose_name='Message')),
                ('newsletter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='user_packages.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='event_invites.Invite'),
        ),
    ]
