# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invites', '0002_auto_20160826_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='num_of_adults',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='num_of_children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
