# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_invites', '0003_auto_20160827_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='attending',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YS', max_length=5),
        ),
    ]
