# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=245)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(max_length=250)),
                ('addressline2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(default='California', max_length=150)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCateringService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ManyToManyField(to='vendors.CateringAmenity')),
            ],
        ),
        migrations.CreateModel(
            name='VendorLocationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.ManyToManyField(to='vendors.LocationAmenity')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vendors.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short_desc', models.CharField(max_length=500)),
                ('price_type', models.CharField(choices=[('PH', 'Per Hour'), ('PP', 'Per Person'), ('PS', 'Per Service')], max_length=2)),
                ('price', models.FloatField()),
                ('detailed_desc', models.TextField()),
                ('duration', models.CharField(max_length=10)),
                ('min_people', models.IntegerField(verbose_name='Minimum Number of People')),
                ('max_people', models.IntegerField(verbose_name='Maximum Number of People')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSocialReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=150)),
                ('num_reviews', models.IntegerField(verbose_name='Number of Reviews')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendorlocationservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_service', to='vendors.VendorService'),
        ),
        migrations.AddField(
            model_name='vendorcateringservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_service', to='vendors.VendorService'),
        ),
    ]
