# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoruser',
            name='users',
        ),
        migrations.AddField(
            model_name='vendor',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VendorUser',
        ),
    ]
