# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorsocialreview_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraddress',
            name='vendor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorcateringservice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorlocationservice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
            preserve_default=False,
        ),
    ]
