# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20160910_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcateringservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catering_service', to='vendors.VendorService'),
        ),
        migrations.AlterField(
            model_name='vendorlocationservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_service', to='vendors.VendorService'),
        ),
    ]
