# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20160910_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcateringservice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorcateringservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='vendorlocationservice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorlocationservice',
            name='service',
        ),
        migrations.AddField(
            model_name='vendorcateringservice',
            name='vendorservice_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.VendorService'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorlocationservice',
            name='vendorservice_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.VendorService'),
            preserve_default=False,
        ),
    ]
