# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendorcateringservice_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcateringservice',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='vendorlocationservice',
            name='photos',
        ),
    ]
