# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20160911_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservicephoto',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 9, 11, 11, 31, 5, 684774, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
    ]
