# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendorservicephoto_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringamenity',
            options={'verbose_name_plural': 'Catering amenities'},
        ),
        migrations.AlterModelOptions(
            name='locationamenity',
            options={'verbose_name_plural': 'Location amenities'},
        ),
    ]
