# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20160703_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selebuser',
            name='is_active',
        ),
    ]
