# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_selebuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='selebuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
